import dynamic from "next/dynamic";
import { type Processes } from "contexts/process/types";
import { TASKBAR_HEIGHT } from "utils/constants";

const directory: Processes = {
  BoxedWine: {
    Component: dynamic(() => import("components/apps/BoxedWine")),
    allowResizing: false,
    backgroundColor: "#000",
    defaultSize: {
      height: 480,
      width: 640,
    },
    dependantLibs: ["/Program Files/BoxedWine/boxedwine.wasm"],
    icon: "/System/Icons/olamov-boxedwine.png",
    libs: [
      "/Program Files/BoxedWine/browserfs.boxedwine.js",
      "/Program Files/BoxedWine/boxedwine-shell.js",
      "/Program Files/BoxedWine/boxedwine.js",
    ],
    lockAspectRatio: true,
    singleton: true,
    title: "BoxedWine",
  },
  Browser: {
    Component: dynamic(() => import("components/apps/Browser")),
    backgroundColor: "#FFF",
    defaultSize: {
      height: 500,
      width: 600,
    },
    icon: "/System/Icons/olamov-browser.png",
    title: "Browser",
  },
  Chess: {
    Component: dynamic(() => import("components/apps/Chess")),
    backgroundColor: "#312E2B",
    defaultSize: {
      height: 567,
      width: 420,
    },
    icon: "/System/Icons/olamov-chess.png",
    libs: ["/Program Files/Chess/chessboard2.min.css"],
    title: "Chess",
  },
  ClassiCube: {
    Component: dynamic(() => import("components/apps/ClassiCube")),
    backgroundColor: "#201E20",
    defaultSize: {
      height: 420,
      width: 640,
    },
    icon: "/System/Icons/olamov-classicube.png",
    libs: ["/Program Files/ClassiCube/ClassiCube.js"],
    title: "ClassiCube",
  },
  DXBall: {
    Component: dynamic(() => import("components/apps/DX-Ball")),
    backgroundColor: "#000",
    icon: "/System/Icons/olamov-dxball.png",
    libs: ["/Program Files/DX-Ball/game.js"],
    lockAspectRatio: true,
    singleton: true,
    title: "DX-Ball",
  },
  DevTools: {
    Component: dynamic(() => import("components/apps/DevTools")),
    backgroundColor: "#242424",
    defaultSize: {
      height: 380,
      width: 545,
    },
    icon: "/System/Icons/olamov-devtools.png",
    libs: [
      "/Program Files/Eruda/eruda.js",
      "/Program Files/Eruda/eruda-monitor.js",
    ],
    singleton: true,
    title: "DevTools",
  },
  Emulator: {
    Component: dynamic(() => import("components/apps/Emulator")),
    backgroundColor: "#000",
    defaultSize: {
      height: 400,
      width: 600,
    },
    dependantLibs: [
      "/Program Files/EmulatorJs/emu-css.min.css",
      "/Program Files/EmulatorJs/emulator.min.js",
    ],
    icon: "/System/Icons/olamov-emulator.png",
    libs: ["/Program Files/EmulatorJs/loader.js"],
    lockAspectRatio: true,
    title: "Emulator",
  },
  FileExplorer: {
    Component: dynamic(() => import("components/apps/FileExplorer")),
    backgroundColor: "#202020",
    defaultSize: {
      height: 325,
      width: 447,
    },
    icon: "/System/Icons/olamov-folder.png",
    title: "File Explorer",
  },
  IRC: {
    Component: dynamic(() => import("components/apps/IRC")),
    backgroundColor: "#FFF",
    defaultSize: {
      height: 512,
      width: 704,
    },
    icon: "/System/Icons/olamov-kiwiirc.png",
    libs: ["/Program Files/kiwiirc/index.html"],
    title: "IRC",
  },
  JSDOS: {
    Component: dynamic(() => import("components/apps/JSDOS")),
    autoSizing: true,
    backgroundColor: "#000",
    defaultSize: {
      height: 200,
      width: 320,
    },
    dependantLibs: ["/Program Files/js-dos/wdosbox.wasm"],
    icon: "/System/Icons/olamov-msdos.png",
    libs: [
      "/Program Files/js-dos/emulators.js",
      "/Program Files/js-dos/emulators-ui.js",
    ],
    lockAspectRatio: true,
    title: "js-dos v7",
  },
  Marked: {
    Component: dynamic(() => import("components/apps/Marked")),
    backgroundColor: "#FFF",
    defaultSize: {
      height: 480,
      width: 560,
    },
    icon: "/System/Icons/olamov-marked.png",
    libs: [
      "/Program Files/Marked/marked.min.js",
      "/Program Files/Marked/purify.min.js",
    ],
    title: "Marked",
  },
  Messenger: {
    Component: dynamic(() => import("components/apps/Messenger")),
    backgroundColor: "#242526",
    defaultSize: {
      height: 500,
      width: 425,
    },
    icon: "/System/Icons/olamov-messenger.png",
    singleton: true,
    title: "Messenger",
  },
  MonacoEditor: {
    Component: dynamic(() => import("components/apps/MonacoEditor")),
    backgroundColor: "#1E1E1E",
    defaultSize: {
      height: 480,
      width: 544,
    },
    dependantLibs: [
      "/Program Files/MonacoEditor/vs/loader.js",
      "/Program Files/MonacoEditor/vs/editor/editor.main.js",
      "/Program Files/MonacoEditor/vs/editor/editor.main.css",
      "/Program Files/MonacoEditor/vs/editor/editor.main.nls.js",
    ],
    icon: "/System/Icons/olamov-monaco.png",
    title: "Monaco Editor",
  },
  Notepad: {
    Component: dynamic(() => import("components/apps/Notepad")),
    backgroundColor: "#c0c0c0",
    defaultSize: {
      height: 360,
      width: 480,
    },
    icon: "/System/Icons/olamov-documents.png",
    title: "Readme.txt - Notepad",
  },
  OpenType: {
    Component: dynamic(() => import("components/apps/OpenType")),
    backgroundColor: "#FFF",
    icon: "/System/Icons/opentype.webp",
    preferProcessIcon: true,
    title: "OpenType",
  },
  OpenWith: {
    Component: dynamic(() => import("components/system/Dialogs/OpenWith")),
    allowResizing: false,
    backgroundColor: "#FFF",
    defaultSize: {
      height: 492,
      width: 392,
    },
    dialogProcess: true,
    hideTaskbarEntry: true,
    hideTitlebar: true,
    icon: "/System/Icons/olamov-unknown.png",
    title: "Open With",
  },
  PDF: {
    Component: dynamic(() => import("components/apps/PDF")),
    backgroundColor: "#525659",
    icon: "/System/Icons/olamov-pdf.png",
    libs: ["/Program Files/PDF.js/pdf.js"],
    title: "PDF",
  },
  Paint: {
    Component: dynamic(() => import("components/apps/Paint")),
    backgroundColor: "#808080",
    icon: "/System/Icons/olamov-paint.png",
    libs: ["/Program Files/jspaint/index.html"],
    title: "Paint",
  },
  Photos: {
    Component: dynamic(() => import("components/apps/Photos")),
    backgroundColor: "#222",
    defaultSize: {
      height: 432,
      width: 576,
    },
    hideTitlebarIcon: true,
    icon: "/System/Icons/olamov-pictures.png",
    title: "Photos",
  },
  Properties: {
    Component: dynamic(() => import("components/system/Dialogs/Properties")),
    allowResizing: false,
    backgroundColor: "rgb(240, 240, 240)",
    defaultSize: {
      height: 412,
      width: 361,
    },
    dialogProcess: true,
    hideMaximizeButton: true,
    hideMinimizeButton: true,
    icon: "",
    title: "Properties",
  },
  Quake3: {
    Component: dynamic(() => import("components/apps/Quake3")),
    backgroundColor: "#000",
    defaultSize: {
      height: 480,
      width: 640,
    },
    icon: "/System/Icons/olamov-quake3.png",
    libs: ["/Program Files/Quake3/Quake3Game.js"],
    lockAspectRatio: true,
    title: "Quake III Arena",
  },
  Ruffle: {
    Component: dynamic(() => import("components/apps/Ruffle")),
    backgroundColor: "#000",
    defaultSize: {
      height: 400,
      width: 550,
    },
    icon: "/System/Icons/olamov-ruffle.png",
    libs: ["/Program Files/Ruffle/ruffle.js"],
    lockAspectRatio: true,
    title: "Ruffle",
  },
  Run: {
    Component: dynamic(() => import("components/system/Dialogs/Run")),
    allowResizing: false,
    defaultSize: {
      height: 174,
      width: 397,
    },
    dialogProcess: true,
    hideMaximizeButton: true,
    hideMinimizeButton: true,
    icon: "/System/Icons/olamov-run.png",
    initialRelativePosition: {
      bottom: TASKBAR_HEIGHT + 11,
      left: 15,
    },
    singleton: true,
    title: "Run",
  },
  ScreenSaver: {
    Component: dynamic(() => import("components/system/Dialogs/ScreenSaver")),
    allowResizing: false,
    dialogProcess: true,
    hasWindow: false,
    hideTaskbarEntry: true,
    icon: "/System/Icons/screensaver.webp",
    singleton: true,
    title: "Screen Saver",
  },
  Shutdown: {
    Component: dynamic(() => import("components/system/Dialogs/Shutdown")),
    allowResizing: false,
    backgroundColor: "#c0c0c0",
    defaultSize: {
      height: 184,
      width: 386,
    },
    dialogProcess: true,
    hideMaximizeButton: true,
    hideMinimizeButton: true,
    icon: "/System/Icons/olamov-shutdown.png",
    singleton: true,
    title: "Shut Down Windows",
  },
  SpaceCadet: {
    Component: dynamic(() => import("components/apps/SpaceCadet")),
    backgroundColor: "#000",
    defaultSize: {
      height: 428,
      width: 600,
    },
    dependantLibs: ["/Program Files/SpaceCadet/SpaceCadetPinball.wasm"],
    icon: "/System/Icons/olamov-pinball.png",
    libs: ["/Program Files/SpaceCadet/SpaceCadetPinball.js"],
    lockAspectRatio: true,
    title: "Space Cadet",
  },
  StableDiffusion: {
    Component: dynamic(() => import("components/apps/StableDiffusion")),
    backgroundColor: "rgb(235, 251, 247)",
    defaultSize: {
      height: 644,
      width: 538,
    },
    icon: "/System/Icons/olamov-stablediffusion.png",
    singleton: true,
    title: "Stable Diffusion",
  },
  Terminal: {
    Component: dynamic(() => import("components/apps/Terminal")),
    backgroundColor: "#000",
    defaultSize: {
      height: 374,
      width: 615,
    },
    icon: "/System/Icons/olamov-terminal.png",
    libs: [
      "/Program Files/Xterm.js/xterm.css",
      "/Program Files/Xterm.js/xterm.js",
      "/Program Files/Xterm.js/xterm-addon-fit.js",
      "/Program Files/Xterm.js/local-echo.js",
    ],
    preferProcessIcon: true,
    title: "Olamov Terminal",
  },
  Tic80: {
    Component: dynamic(() => import("components/apps/Tic80")),
    backgroundColor: "#1A1C2C",
    defaultSize: {
      height: 346,
      width: 615,
    },
    dependantLibs: ["/Program Files/Tic80/tic80.wasm"],
    icon: "/System/Icons/olamov-tic80.png",
    libs: ["/Program Files/Tic80/tic80.js"],
    lockAspectRatio: true,
    title: "TIC-80 tiny computer",
  },
  TinyMCE: {
    Component: dynamic(() => import("components/apps/TinyMCE")),
    backgroundColor: "#202124",
    dependantLibs: [
      "/Program Files/TinyMCE/themes/silver/theme.min.js",
      "/Program Files/TinyMCE/models/dom/model.min.js",
      "/Program Files/TinyMCE/icons/default/icons.min.js",
      "/Program Files/TinyMCE/skins/ui/oxide/skin.min.css",
    ],
    icon: "/System/Icons/olamov-tinymce.png",
    libs: ["/Program Files/TinyMCE/tinymce.min.js"],
    title: "TinyMCE",
  },
  Transfer: {
    Component: dynamic(() => import("components/system/Dialogs/Transfer")),
    allowResizing: false,
    backgroundColor: "#FFF",
    defaultSize: {
      height: 163,
      width: 400,
    },
    dialogProcess: true,
    icon: "/System/Icons/olamov-copying.png",
    title: "",
  },
  V86: {
    Component: dynamic(() => import("components/apps/V86")),
    allowResizing: false,
    autoSizing: true,
    backgroundColor: "#000",
    defaultSize: {
      height: 200,
      width: 320,
    },
    dependantLibs: ["/Program Files/Virtual x86/v86.wasm"],
    icon: "/System/Icons/olamov-v86.png",
    libs: ["/Program Files/Virtual x86/libv86.js"],
    preferProcessIcon: true,
    title: "Virtual x86",
  },
  VideoPlayer: {
    Component: dynamic(() => import("components/apps/VideoPlayer")),
    autoSizing: true,
    backgroundColor: "#000",
    defaultSize: {
      height: 390,
      width: 640,
    },
    icon: "/System/Icons/olamov-video.png",
    libs: [
      "/Program Files/Video.js/video-js.min.css",
      "/Program Files/Video.js/video.min.js",
      "/Program Files/Video.js/Youtube.min.js",
    ],
    title: "Video Player",
  },
  Vim: {
    Component: dynamic(() => import("components/apps/Vim")),
    allowResizing: false,
    backgroundColor: "#222324",
    defaultSize: {
      height: 448,
      width: 595,
    },
    icon: "/System/Icons/olamov-vim.png",
    libs: ["/Program Files/Vim.js/vim.js"],
    singleton: true,
    title: "Vim",
  },
  Webamp: {
    Component: dynamic(() => import("components/apps/Webamp")),
    allowResizing: false,
    hasWindow: false,
    icon: "/System/Icons/olamov-webamp.png",
    libs: ["/Program Files/Webamp/webamp.bundle.min.js"],
    singleton: true,
    title: "Webamp",
  },
  olamovStream: {
    Component: dynamic(() => import("components/apps/olamovStream")),
    backgroundColor: "#1d1233",
    defaultSize: {
      height: 480,
      width: 720,
    },
    icon: "/System/Icons/olamov-stream.png",
    title: "olamovStream",
  },
};

export default directory;
